### ISSUE TITLE
Do not have .brat file for brat2conllu.pl

### ISSUE THREAD

**Issue by leugh** [UniversalDependencies/cairo#1]
Hi.

The documentation for brat2conllu.pl shows as an example to use ru.txt and ru.brat as input. From brat I can only export ".ann" files, but I do not have any .brat files. Art those the same? I renamed my .ann files to .brat and it _seems_ to work.

Thanks!

**Comment by dan-zeman** [comment]
Yes it should be `.ann`. Even the scripts in this repo actually use `.ann`, albeit some comment lines mentioned `.brat`. Perhaps a mistake from the time when I was starting to investigate the format. Fixed in b971c30c67bc61df9feb9c8086c48209d6b1f8fd.
