### ISSUE TITLE
brat2conllu.pl Does Not Output Dependency Relations

### ISSUE THREAD

**Issue by FlorianPfisterer** [UniversalDependencies/cairo#3]
We have used [brat's universal dependencies configuration](https://github.com/nlplab/brat/tree/master/configurations/Universal-Dependencies) (slightly adjusted with some renamed/added dependency relations) in brat v1.3 to annotate dependency relations and POS-tags in a small dataset. 

After acquiring the brat-standoff-formatted `.ann` files, I ran [the `brat2conllu.pl` script](https://github.com/UniversalDependencies/cairo/blob/master/weaver/brat2conllu.pl) on them, but the resulting CoNLL-U formatted data lacks dependency structure and dependency relation labels. 

#### Plain Text (`example.txt`)
```
in a bowl .
```

#### Brat Standoff Annotation (`example.ann`)
```
T1.1	ADP 0 2	in
R1.1-1	case Arg1:T1.3 Arg2:T1.1
#1.1	AnnotatorNotes T1.1	LEMMA=in POSTAG=IN
T1.2	DET 3 4	a
A1.2-1	Definite T1.2 Ind
A1.2-2	PronType T1.2 Art
R1.2-1	det Arg1:T1.3 Arg2:T1.2
#1.2	AnnotatorNotes T1.2	LEMMA=a POSTAG=DT
T1.3	NOUN 5 9	bowl
A1.3-1	Number T1.3 Sing
#1.3	AnnotatorNotes T1.3	LEMMA=bowl POSTAG=NN
T1.4	PUNCT 10 11	.
R1.4-1	punct Arg1:T1.3 Arg2:T1.4
#1.4	AnnotatorNotes T1.4	LEMMA=. POSTAG=.
```

#### `brat2conllu.pl` Output (`example.conllu`)
Running `perl brat2conllu.pl example.txt example.ann > example.conllu` yields:
```
# sent_id = s1
# text = in a bowl .
1	in	_	ADP	_	_	0	_	_	Offset=0-2
2	a	_	DET	_	Definite=Ind|PronType=Art	0	_	_	Offset=3-4
3	bowl	_	NOUN	_	Number=Sing	0	_	_	Offset=5-9
4	.	_	PUNCT	_	_	0	_	_	Offset=10-11
```

* **Expected**: the CoNLL-U output contains the correct dependency labels and structure.
* **Actual**: as you can see, all words have 0 as their head (i.e. all words are roots) and the dependency labels are completely left out.

**Question**: what are we doing wrong? Does the script expect another version of the brat standoff format?

**Comment by dan-zeman** [comment]
The script was created for and tested on brat-annotated files from an on-line UD test annotation server, which was set up and used in 2015 (it was taken down recently). The [weaver folder](https://github.com/UniversalDependencies/cairo/tree/master/weaver) where the script lives also contains a number of `.ann` files and their `.conllu` conversions. Are there any differences between those and your `.ann` files?

**Comment by FlorianPfisterer** [comment]
Thanks for the fast reply!

I just went through some`.ann` files and found that they don't use dots in the names of tags/relations/attributes. So I renamed the tag names in a sample `.ann` file (e.g. `T1.1` is renamed to `T11`) and then the CoNLL-U conversion worked.

So the `brat2conllu.pl` script seems to have difficulty understanding relation lines when the arguments (tag names) have dots in them. Is there an easy fix for the script or do we need to rename our tags? (Sorry I am not familiar with Perl)

**Comment by dan-zeman** [comment]
I, on the other hand, am not familiar with brat :-) (at least I forgot what I found out when writing the script) but it seems like a change to [this line](https://github.com/UniversalDependencies/cairo/blob/a78539df901668338a84e22ac1fa331577d83087/weaver/brat2conllu.pl#L85) could help. "`(T\d+)`" says that "T" must be followed by one or more digits. If changed to "`(T[\d\.]+)`", it will allow one or more digits or dots. Note that the pattern occurs twice on the line. Let me know if it works for you – in that case I will modify the script in the repository, which might help other people.

**Comment by FlorianPfisterer** [comment]
Perfect, it works now. I've created a PR so you don't have to change it yourself.
Thank you very much for your fast, targeted help!
